version: "3.3"

services:
    blog:
        image: "jekyll/minimal:3.5"
        command: jekyll serve
        volumes:
              - "$PWD:/srv/jekyll"
        ports:
            - "4000:4000"
            - "35729:35729"
            - "3000:3000"